# This is a basic workflow to help you get started with Actions

name: Python greetings


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: 'World'
        description: 'Name input'
        required: true
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  install-pip-deps:
    runs-on: self-hosted
    
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Installing pip dependencies.
        
      - name: Call actions repository
        uses: actions/checkout@v6
        
      - name: Repository-cloning
        uses: actions/checkout@v6
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          
      - name: Create-virtual-environment
        working-directory: python-greetings
        run: python -m venv venv
        
      - name: Install-libraries
        working-directory: python-greetings
        run: .\venv\Scripts\python -m pip install -r requirements.txt
        
  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Check node version
        run: echo Deploying to dev.
        
  tests-on-dev:
    needs: deploy-to-dev
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Testing on dev.
        
  deploy-to-stg:
    needs: tests-on-dev
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Deploying to staging.
        
  tests-on-stg:
    needs: deploy-to-stg
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Testing on staging.
        
  deploy-to-preprod:
    needs: tests-on-stg
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Deploying to preprod
        
  tests-on-preprod:
    needs: deploy-to-preprod
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Testing on preprod.
        
  deploy-to-prod:
    needs: tests-on-preprod
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Deploying to prod.
        
  tests-on-prod:
    needs: deploy-to-prod
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print-info
        run: echo Testing on prod.
