# This is a basic workflow to help you get started with Actions
name: Python greetings


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Installing pip dependencies.

      - name: Install Python dependencies
        uses: ./pipeline/.github/actions/install-python-deps


  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Deploying to  dev.

      - name: Deploy to dev
        uses: ./pipeline/.github/actions/deploy-python-service
        with:
          env_name: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Testing on dev.

      - name: Run dev tests
        uses: ./pipeline/.github/actions/test-greetings
        with:
          env_name: dev

  deploy-to-stg:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Deploying to stg.

      - name: Deploy to stg
        uses: ./pipeline/.github/actions/deploy-python-service
        with:
          env_name: stg
          port: 7002

  tests-on-stg:
    needs: deploy-to-stg
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Testing on stg.

      - name: Run stg tests
        uses: ./pipeline/.github/actions/test-greetings
        with:
          env_name: stg

  deploy-to-preprod:
    needs: tests-on-stg
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Deploying to preprod.

      - name: Deploy to preprod
        uses: ./pipeline/.github/actions/deploy-python-service
        with:
          env_name: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      # Runs a single command using the runners shell
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Testing on preprod.

      - name: Run preprod tests
        uses: ./pipeline/.github/actions/test-greetings
        with:
          env_name: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Deploying to prod.

      - name: Deploy to prod
        uses: ./pipeline/.github/actions/deploy-python-service
        with:
          env_name: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repository
        uses: actions/checkout@v6
        with:
          path: pipeline
          clean: false

      - name: Print-info
        run: echo Testing on prod.

      - name: Run prod tests
        uses: ./pipeline/.github/actions/test-greetings
        with:
          env_name: prod
